::object\retroparse_test.exe "test"        1> "test\actual\test.txt"
::object\retroparse_test.exe "halfinning"  1> "test\actual\halfinning.txt"
::object\retroparse_test.exe "line 272"    1> "test\actual\line 272.txt"
::object\retroparse_test.exe "scoring"     1> "test\actual\scoring.txt"
::object\retroparse_test.exe "2000NYA_all" 1> "test\actual\2000NYA_all.txt"
goto start
object\retroparseGroup_test.exe "test\script\grp_2000ANA_all.txt" 1> "test\actual\grp_2000ANA_all.txt" 2> "test\actual\grp_2000ANA_all.err"
object\retroparseGroup_test.exe "test\script\grp_2000ARI_all.txt" 1> "test\actual\grp_2000ARI_all.txt" 2> "test\actual\grp_2000ARI_all.err"
object\retroparseGroup_test.exe "test\script\grp_2000ATL_all.txt" 1> "test\actual\grp_2000ATL_all.txt" 2> "test\actual\grp_2000ATL_all.err"
object\retroparseGroup_test.exe "test\script\grp_2000BAL_all.txt" 1> "test\actual\grp_2000BAL_all.txt" 2> "test\actual\grp_2000BAL_all.err"
object\retroparseGroup_test.exe "test\script\grp_2000BOS_all.txt" 1> "test\actual\grp_2000BOS_all.txt" 2> "test\actual\grp_2000BOS_all.err"
object\retroparseGroup_test.exe "test\script\grp_2000CHA_all.txt" 1> "test\actual\grp_2000CHA_all.txt" 2> "test\actual\grp_2000CHA_all.err"
object\retroparseGroup_test.exe "test\script\grp_2000CHN_all.txt" 1> "test\actual\grp_2000CHN_all.txt" 2> "test\actual\grp_2000CHN_all.err"
object\retroparseGroup_test.exe "test\script\grp_2000CIN_all.txt" 1> "test\actual\grp_2000CIN_all.txt" 2> "test\actual\grp_2000CIN_all.err"
object\retroparseGroup_test.exe "test\script\grp_2000CLE_all.txt" 1> "test\actual\grp_2000CLE_all.txt" 2> "test\actual\grp_2000CLE_all.err"
object\retroparseGroup_test.exe "test\script\grp_2000COL_all.txt" 1> "test\actual\grp_2000COL_all.txt" 2> "test\actual\grp_2000COL_all.err"
object\retroparseGroup_test.exe "test\script\grp_2000DET_all.txt" 1> "test\actual\grp_2000DET_all.txt" 2> "test\actual\grp_2000DET_all.err"
object\retroparseGroup_test.exe "test\script\grp_2000FLO_all.txt" 1> "test\actual\grp_2000FLO_all.txt" 2> "test\actual\grp_2000FLO_all.err"
object\retroparseGroup_test.exe "test\script\grp_2000HOU_all.txt" 1> "test\actual\grp_2000HOU_all.txt" 2> "test\actual\grp_2000HOU_all.err"
object\retroparseGroup_test.exe "test\script\grp_2000KCA_all.txt" 1> "test\actual\grp_2000KCA_all.txt" 2> "test\actual\grp_2000KCA_all.err"
object\retroparseGroup_test.exe "test\script\grp_2000LAN_all.txt" 1> "test\actual\grp_2000LAN_all.txt" 2> "test\actual\grp_2000LAN_all.err"
object\retroparseGroup_test.exe "test\script\grp_2000MIL_all.txt" 1> "test\actual\grp_2000MIL_all.txt" 2> "test\actual\grp_2000MIL_all.err"
object\retroparseGroup_test.exe "test\script\grp_2000MIN_all.txt" 1> "test\actual\grp_2000MIN_all.txt" 2> "test\actual\grp_2000MIN_all.err"
object\retroparseGroup_test.exe "test\script\grp_2000MON_all.txt" 1> "test\actual\grp_2000MON_all.txt" 2> "test\actual\grp_2000MON_all.err"
object\retroparseGroup_test.exe "test\script\grp_2000NYA_all.txt" 1> "test\actual\grp_2000NYA_all.txt" 2> "test\actual\grp_2000NYA_all.err"
object\retroparseGroup_test.exe "test\script\grp_2000NYN_all.txt" 1> "test\actual\grp_2000NYN_all.txt" 2> "test\actual\grp_2000NYN_all.err"
object\retroparseGroup_test.exe "test\script\grp_2000OAK_all.txt" 1> "test\actual\grp_2000OAK_all.txt" 2> "test\actual\grp_2000OAK_all.err"
object\retroparseGroup_test.exe "test\script\grp_2000PHI_all.txt" 1> "test\actual\grp_2000PHI_all.txt" 2> "test\actual\grp_2000PHI_all.err"
object\retroparseGroup_test.exe "test\script\grp_2000PIT_all.txt" 1> "test\actual\grp_2000PIT_all.txt" 2> "test\actual\grp_2000PIT_all.err"
object\retroparseGroup_test.exe "test\script\grp_2000SDN_all.txt" 1> "test\actual\grp_2000SDN_all.txt" 2> "test\actual\grp_2000SDN_all.err"
object\retroparseGroup_test.exe "test\script\grp_2000SEA_all.txt" 1> "test\actual\grp_2000SEA_all.txt" 2> "test\actual\grp_2000SEA_all.err"
object\retroparseGroup_test.exe "test\script\grp_2000SFN_all.txt" 1> "test\actual\grp_2000SFN_all.txt" 2> "test\actual\grp_2000SFN_all.err"
object\retroparseGroup_test.exe "test\script\grp_2000SLN_all.txt" 1> "test\actual\grp_2000SLN_all.txt" 2> "test\actual\grp_2000SLN_all.err"
object\retroparseGroup_test.exe "test\script\grp_2000TBA_all.txt" 1> "test\actual\grp_2000TBA_all.txt" 2> "test\actual\grp_2000TBA_all.err"
object\retroparseGroup_test.exe "test\script\grp_2000TEX_all.txt" 1> "test\actual\grp_2000TEX_all.txt" 2> "test\actual\grp_2000TEX_all.err"
object\retroparseGroup_test.exe "test\script\grp_2000TOR_all.txt" 1> "test\actual\grp_2000TOR_all.txt" 2> "test\actual\grp_2000TOR_all.err"
object\retroparseGroup_test.exe "test\script\grp_2000.txt" 1> "test\actual\grp_2000.txt" 2> "test\actual\grp_2000.err"
object\retroparseGroup_test.exe "test\script\grp_2022.txt" 1> "test\actual\grp_2022.txt" 2> "test\actual\grp_2022.err"
object\retroBinMerge.exe "test\script\retroBinMerge.txt" 1> "test\actual\retroBinMerge.txt" 2> "test\actual\retroBinMerge.err"
object\retroBin2HTML.exe "test\actual\grp_2000ANA_all.bin"
object\retroBin2HTML.exe "test\actual\grp_2000ARI_all.bin"
object\retroBin2HTML.exe "test\actual\grp_2000ATL_all.bin"
object\retroBin2HTML.exe "test\actual\grp_2000BAL_all.bin"
object\retroBin2HTML.exe "test\actual\grp_2000BOS_all.bin"
object\retroBin2HTML.exe "test\actual\grp_2000CHA_all.bin"
object\retroBin2HTML.exe "test\actual\grp_2000CHN_all.bin"
object\retroBin2HTML.exe "test\actual\grp_2000CIN_all.bin"
object\retroBin2HTML.exe "test\actual\grp_2000CLE_all.bin"
object\retroBin2HTML.exe "test\actual\grp_2000COL_all.bin"
object\retroBin2HTML.exe "test\actual\grp_2000DET_all.bin"
object\retroBin2HTML.exe "test\actual\grp_2000FLO_all.bin"
object\retroBin2HTML.exe "test\actual\grp_2000HOU_all.bin"
object\retroBin2HTML.exe "test\actual\grp_2000KCA_all.bin"
object\retroBin2HTML.exe "test\actual\grp_2000LAN_all.bin"
object\retroBin2HTML.exe "test\actual\grp_2000MIL_all.bin"
object\retroBin2HTML.exe "test\actual\grp_2000MIN_all.bin"
object\retroBin2HTML.exe "test\actual\grp_2000MON_all.bin"
object\retroBin2HTML.exe "test\actual\grp_2000NYA_all.bin"
object\retroBin2HTML.exe "test\actual\grp_2000NYN_all.bin"
object\retroBin2HTML.exe "test\actual\grp_2000OAK_all.bin"
object\retroBin2HTML.exe "test\actual\grp_2000PHI_all.bin"
object\retroBin2HTML.exe "test\actual\grp_2000PIT_all.bin"
object\retroBin2HTML.exe "test\actual\grp_2000SDN_all.bin"
object\retroBin2HTML.exe "test\actual\grp_2000SEA_all.bin"
object\retroBin2HTML.exe "test\actual\grp_2000SFN_all.bin"
object\retroBin2HTML.exe "test\actual\grp_2000SLN_all.bin"
object\retroBin2HTML.exe "test\actual\grp_2000TBA_all.bin"
object\retroBin2HTML.exe "test\actual\grp_2000TEX_all.bin"
object\retroBin2HTML.exe "test\actual\grp_2000TOR_all.bin"
object\retroBin2HTML.exe "test\actual\grp_2000.bin"
object\retroBin2HTML.exe "test\actual\grp_2022.bin"
:start
object\retroparseGroup_test.exe "test\script\grp_1999-2002.txt" 1> "test\actual\grp_1999-2002.txt" 2> "test\actual\grp_1999-2002.err"
goto :eof
