fname <- 'C:/Users/Kevin/source/repos/Retro/RetroEventMaestro/2021eve/2021TOR.EVA.txt'
colnames <- c(
'game id',
'visiting team',
'inning',
'batting team',
'outs',
'balls',
'strikes',
'pitch sequence',
'vis score',
'home score',
'batter',
'batter hand',
'res batter',
'res batter hand',
'pitcher',
'pitcher hand',
'res pitcher',
'res pitcher hand',
'catcher',
'first base',
'second base',
'third base',
'shortstop',
'left field',
'center field',
'right field',
'first runner',
'second runner',
'third runner',
'event text',
'leadoff flag',
'pinchhit flag',
'defensive position',
'lineup position',
'event type',
'batter event flag',
'ab flag',
'hit value',
'SH flag',
'SF flag',
'outs on play',
'double play flag',
'triple play flag',
'RBI on play',
'wild pitch flag',
'passed ball flag',
'fielded by',
'batted ball type',
'bunt flag',
'foul flag',
'hit location',
'num errors',
'1st error player',
'1st error type',
'2nd error player',
'2nd error type',
'3rd error player',
'3rd error type',
'batter dest',
'runner on 1st dest',
'runner on 2nd dest',
'runner on 3rd dest',
'play on batter',
'play on runner on 1st',
'play on runner on 2nd',
'play on runner on 3rd',
'SB for runner on 1st flag',
'SB for runner on 2nd flag',
'SB for runner on 3rd flag',
'CS for runner on 1st flag',
'CS for runner on 2nd flag',
'CS for runner on 3rd flag',
'PO for runner on 1st flag',
'PO for runner on 2nd flag',
'PO for runner on 3rd flag',
'Responsible pitcher for runner on 1st',
'Responsible pitcher for runner on 2nd',
'Responsible pitcher for runner on 3rd',
'New Game Flag',
'End Game Flag',
'Pinch-runner on 1st',
'Pinch-runner on 2nd',
'Pinch-runner on 3rd',
'Runner removed for pinch-runner on 1st',
'Runner removed for pinch-runner on 2nd',
'Runner removed for pinch-runner on 3rd',
'Batter removed for pinch-hitter',
'Position of batter removed for pinch-hitter',
'Fielder with First Putout',
'Fielder with Second Putout',
'Fielder with Third Putout',
'Fielder with First Assist',
'Fielder with Second Assist',
'Fielder with Third Assist',
'Fielder with Fourth Assist',
'Fielder with Fifth Assist',
'event num')
f <- read.csv(file = fname, header = FALSE, quote = "\"", col.names=colnames)

r <- function(t) {
  x <- 0
  for (i in 1:10) {
    x = x + i
  }
}

aaSeq <- function(p) {
  X <- 0
  out <- vector("list", 0)
  for (i in 1:stringr::str_length(p)) {
    switch (substring (p, i, i),
            'A' = X <- X + 1,
            'C' = X <- X + 1,
            'F' = X <- X + 1,
            'K' = X <- X + 1,
            'L' = X <- X + 1,
            'M' = X <- X + 1,
            'O' = X <- X + 1,
            'Q' = X <- X + 1,
            'R' = X <- X + 1,
            'S' = X <- X + 1,
            'T' = X <- X + 1,
            'X' = X <- X + 1,
            'Y' = X <- X + 1,
            'B' = X <- X + 0x100,
            'I' = X <- X + 0x100,
            'P' = X <- X + 0x100,
            'V' = X <- X + 0x100,
            'H' = X <- X + 0x100)
    out <- c(out, X)
  }
  c(out, recursive=TRUE, use.names=FALSE)
}
aaSeq(SFN[[1]]$play$pitches[1])
